AllCops:
  TargetRubyVersion: 3.3.0
  NewCops: enable
  Exclude:
    - bin/*
    - vendor/bundle/**/*
    - db/**/*

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
